# Generated by Django 5.1 on 2024-09-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view'), ('can_create', 'Can create'), ('can_edit', 'Can edit'), ('can_delete', 'Can delete')]},
        ),
    ]
