# Generated by Django 5.1 on 2024-09-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='field',
            new_name='post_tags',
        ),
    ]
